name: Build and Publish Release

on:
  push:
    tags:
      - '**'
  workflow_call:
    secrets:
      MODRINTH_TOKEN:
        description: 'The token to use for Modrinth authentication'
        required: true
    inputs:
      version:
        required: true
        type: string
        description: 'Version to release (ex: 1.0.0-1.20.1)'
      mod_version:
        required: true
        type: string
        description: 'Mod version to release (ex: 1.0.0)'
      minecraft_version:
        required: true
        type: string
        description: 'Minecraft version to release (ex: 1.20.1)'

permissions:
  contents: write
  id-token: write
  attestations: write

env:
  RELEASED_VERSION: "${{ inputs.version || github.ref_name }}"
  MOD_VERSION: "${{ inputs.mod_version }}"
  MINECRAFT_VERSION: "${{ inputs.minecraft_version }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: make build

    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: builed-jar
        path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: builed-jar
        path: build/libs
    - uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: 1DmOAPcC
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        github-tag: ${{ env.RELEASED_VERSION }}
        github-generate-changelog: true
        github-draft: false
        github-prerelease: false
        github-token: ${{ secrets.GITHUB_TOKEN }}

        name: Resource Pack Refresher ${{ env.MOD_VERSION }} for Minecraft ${{ env.MINECRAFT_VERSION }}
        version: ${{ env.RELEASED_VERSION }}
        version-type: release
        files: |
            build/libs/resourcepackrefresher*.jar
        loaders: |
          fabric
        game-versions: |
          ${{ env.MINECRAFT_VERSION }}

  
  attestations:
    needs: [build, release]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: builed-jar
        path: build/libs
    - name: Create Attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ResourcePackRefresher-${{ env.RELEASED_VERSION }}.jar
        subject-path: build/libs/resourcepackrefresher*
