name: Build and Publish Release

on:
  push:
    tags:
      - '**'
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: 'Version to release (ex: 1.0.0-1.20.1)'

permissions:
  contents: write
  id-token: write
  attestations: write

env:
  RELEASED_VERSION: "${{ inputs.version || github.ref_name }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: make build

    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: builed-jar
        path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: builed-jar
        path: build/libs
    - run: ls -lR .
    - name: Create Release
      id: create-release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/libs/resourcepackrefresher*
        tag_name: ${{ env.RELEASED_VERSION }}
        name: Release ${{ env.RELEASED_VERSION }}
        generate_release_notes: true
        make_latest: true
        draft: false
        prerelease: false
  
  attestations:
    needs: [build, release]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: builed-jar
        path: build/libs
    - name: Create Attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ResourcePackRefresher-${{ env.RELEASED_VERSION }}.jar
        subject-path: build/libs/resourcepackrefresher*
